name: Deploy to GCS bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if frontend directory has changed
      id: check_changes
      run: |
        git diff --exit-code --quiet frontend || echo "Changes detected in frontend directory"
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
      if: steps.check_changes.outputs.changed == 'true'

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      if: steps.check_changes.outputs.changed == 'true'

    - name: Upload to GCS
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: 'frontend'
        destination: 'lawsoc-prod-0'
      if: steps.check_changes.outputs.changed == 'true'
